env:
  global:
    - secure: AcA/m4tu71bWiUtdQkmEBWQy02HmPZ7i1dzMgXYeXdMEPqRHUZJybO8qFgVdlwP7n9PkENdsnHfMRqzmoTV2qfZHod0UppzFEEKu6jJagegG1OxzJx+i1URHNxY8CqH0r8vDTKeB15O6Pbk7ND0EVM7/h+fFEU4QVRjUU3cYmHeKA7pDJNTHgNYaNqvNYJaVupGKRlQNQN3dvBMTRKkp/nHydUTmAeG30J5fw/YA7tmN0EIcKdLujiLrlL1+z26f3BSrA9uunus2cr3OJKyzrbkuZ7bpjQ9MFkBrjKoF8zHvi6WKgQ0Y67Mw/fC+LAFr8zomSettdeJszx6HbQuYLzpwka89/LN3E9y8xYcuKjQqf8NrFEDNYr9je+AF9HdXfjaVlxeQj13jbeUjmuetE8Ku/zlr2fcTPgAGroVilxBeNLAVpnY/8MxwNrwUeqexx6RW4DkUkZKYuidLzEj5p5JZHKjAEjHwThczS7IhUksPDXQVMdUHzWV/b5bb1dYTPkbHJ7DshU/uWneOiLg/O0Eohuxn10IIdhLyuU3HzeoNA9zBeFRF1uXAWhzGiUEjiG+nBxJk1AaaoTudRx34zpUqB8Okjy7iQjkrsNajcvZqxKAX1V9YPN/WeKYUsh9nrIg8RwopFPAo+soSGvUHeemjFwjM8bGPi+oPBXLLkS8=
    - secure: GQTZsWgZCOno4HV190eblwInp+D01SlvL425Acai+YAfrw6WK8PHMPkNpueofVJadwBAX7e72wuSjNGd1yOnix0RUnweAvWq+uVEvzfe4vMftrFmC7m3hdZ/lpcHdkUQcM0qx+pT6FvB9537vz7bgZz/COe8lw3dv/Ng3bU5QbQG841zDU43eyOtYFq4PoMdPHkK6u4bcjUDG8uEKewDmYtsC/7hfKmXk2t5HD+6F9gaPGLVX+R9Gl1kFpZF7m0GQHFde23l85C1OTxtclRzqH3B6ddTUmHVxyeUh7y++jQ7ejqHAFK6KUAKSEQG6MCJ7yisiiM4j4qeFa7RZel5JxA/8L+nYWhgOztRZpRJHp/RKgiuifVC7V/cZcVNSskGmv2FZUyKLdJaOuQjqy/CAAUAbx2VFxD2gOiB6Ll8lW0Y6vsLT1mknvCDtp5sDHthGRYmKalo6KJT5rdffkMsPH0kujs252aUkd4YzRBvg4d9clu8IUlGemis4SIoBYp18KcAeKKpndXmpa6vfGrSoUXcL8zsTi4pCcIVlckfN04Hu97XKQyTQ/w9RJr/zfpBxjRvdMvBVEljjeflD8NSd3NnISsbahdv2osgTjy8Kp0borzo4Yzc93hsxGryRSPZw3VqS+HWZ6ZobSIlhSrZ2ng9cQFTqfwObqPyAGEY3qk=
language: android
jdk:
  - oraclejdk8
android:
  components:
    - build-tools-23
    - build-tools-24
    - android-23
